#!/usr/bin/env bash
# Publishes the built dashboard to the `hostinger-deploy` branch, which
# Hostinger deploys from directly via its Git integration.
#
# Run via `bun run deploy:hostinger` from apps/web.
#
# WHY A SEPARATE BRANCH, rather than pointing Hostinger at main:
# Hostinger clones the repo and unconditionally runs `npm install` in the
# application root. Against main that reads the monorepo root package.json,
# follows "workspaces": ["apps/*", "packages/*"] into apps/api and packages/db,
# and dies on Bun's workspace protocol, which npm does not implement:
#   npm error code EUNSUPPORTEDPROTOCOL
#   npm error Unsupported URL Type "workspace:": workspace:*
# There is no Hostinger setting that skips that install step, and rewriting the
# backend packages to npm-compatible specifiers would mean changing dependency
# resolution for the working Docker/Bun deployment on the VPS just to satisfy
# the frontend host. Shipping the already-built output on its own branch avoids
# touching any of that: the branch's root package.json declares no dependencies
# at all, so npm install has nothing to resolve and can never reach a
# workspace: reference.
#
# The branch therefore holds BUILD OUTPUT, including a vendored node_modules —
# deliberately, since the whole point is that the host installs nothing. It is
# an orphan branch (no shared history with main) and is force-pushed on every
# deploy; never merge it into main and never branch off it.
set -euo pipefail
cd "$(dirname "$0")/.."

BRANCH="hostinger-deploy"
REPO_ROOT="$(git rev-parse --show-toplevel)"

# Refuse to publish a build made from a dirty tree — the branch records the
# commit it came from, and that reference has to mean something.
if [ -n "$(git status --porcelain)" ]; then
  echo "error: working tree is dirty. Commit or stash first — the deploy branch records the source commit it was built from." >&2
  git status --short >&2
  exit 1
fi

SOURCE_COMMIT="$(git rev-parse --short HEAD)"
SOURCE_BRANCH="$(git rev-parse --abbrev-ref HEAD)"

echo "==> Building from $SOURCE_BRANCH@$SOURCE_COMMIT"
npx next build

echo "==> Preparing standalone output"
bash scripts/prepare-standalone.sh

STAGING=".next/standalone"
if [ ! -f "$STAGING/server.js" ] || [ ! -f "$STAGING/package.json" ]; then
  echo "error: prepare-standalone.sh did not produce a root server.js + package.json" >&2
  exit 1
fi

# A worktree keeps this entirely off the current checkout: main's files are
# never touched, and the orphan branch is assembled in its own directory.
WORKTREE="$(mktemp -d)/deploy"
cleanup() {
  git -C "$REPO_ROOT" worktree remove --force "$WORKTREE" 2>/dev/null || true
}
trap cleanup EXIT

echo "==> Assembling $BRANCH worktree"
if git -C "$REPO_ROOT" show-ref --verify --quiet "refs/heads/$BRANCH"; then
  git -C "$REPO_ROOT" worktree add --force "$WORKTREE" "$BRANCH" >/dev/null
  # Clear the previous deploy so removed files don't linger.
  find "$WORKTREE" -mindepth 1 -maxdepth 1 -not -name '.git' -exec rm -rf {} +
else
  git -C "$REPO_ROOT" worktree add --force --detach "$WORKTREE" >/dev/null
  git -C "$WORKTREE" checkout --orphan "$BRANCH" >/dev/null 2>&1
  git -C "$WORKTREE" rm -rf --cached . >/dev/null 2>&1 || true
  find "$WORKTREE" -mindepth 1 -maxdepth 1 -not -name '.git' -exec rm -rf {} +
fi

cp -R "$STAGING/." "$WORKTREE/"

# node_modules is ignored repo-wide on main; on this branch it IS the payload.
cat > "$WORKTREE/.gitignore" <<'EOF'
# Intentionally empty. This branch ships build output, including a vendored
# node_modules — that is the entire point (the host installs nothing).
EOF

cat > "$WORKTREE/README.md" <<EOF
# hostinger-deploy — generated branch, do not edit by hand

Pre-built Next.js standalone output for the CITS WhatsApp Communication
Manager dashboard, deployed to Hostinger via its Git integration.

Generated by \`apps/web/scripts/deploy-hostinger.sh\` from
\`$SOURCE_BRANCH@$SOURCE_COMMIT\`. Force-pushed on every deploy — never
merge this into \`main\` and never branch off it. Edit the source on
\`main\` and re-run the script.

## Hostinger settings

| Setting | Value |
| --- | --- |
| Branch | \`$BRANCH\` |
| Startup file | \`server.js\` |
| Build command | *(leave empty)* |
| Install command | *(leave empty)* |

Nothing needs installing or building: dependencies are vendored in
\`node_modules/\`, and the root \`package.json\` declares none, so an
unconditional \`npm install\` has nothing to resolve. Its \`build\` script is
a deliberate no-op so an unconditional \`npm run build\` also succeeds.

## Required environment variables

\`\`\`
API_BASE_URL=https://api.wacits.cyberlative.com
API_SHARED_SECRET=<must match the API's own API_SHARED_SECRET>
WORKSPACE_SLUG=cits-internal
\`\`\`

The dashboard renders entirely server-side and calls the API with that
shared secret, so the browser never receives it. Without it every page
fails to render.
EOF

git -C "$WORKTREE" add -A
if git -C "$WORKTREE" diff --cached --quiet; then
  echo "==> No changes since the last deploy — nothing to push."
  exit 0
fi

git -C "$WORKTREE" commit -q -m "build: dashboard from $SOURCE_BRANCH@$SOURCE_COMMIT

Generated by apps/web/scripts/deploy-hostinger.sh. Pre-built Next.js
standalone output with vendored node_modules — Hostinger installs and
builds nothing."

echo "==> Pushing $BRANCH to origin"
git -C "$WORKTREE" push --force origin "$BRANCH"

echo
echo "Deployed $SOURCE_BRANCH@$SOURCE_COMMIT to origin/$BRANCH."
echo "In Hostinger: deploy from branch '$BRANCH', startup file 'server.js',"
echo "build and install commands EMPTY."
