// PRD Appendix A — the full error classification table, exactly as
// specified: keyed on (api_surface, code[, subcode]), never on code alone
// (DM-27/APP-3). Loaded as seed data so it is editable by an administrator
// without a deploy (TS-9) — this file is the ONE-TIME seed, not the source
// of truth once the database is running.
export const ERROR_CODE_SEED = [
  { apiSurface: "*", code: "4", title: "App-level rate limit hit", errorClass: "RETRY_BACKOFF", userFacingExplanation: "Exponential backoff with jitter." },
  { apiSurface: "*", code: "80007", title: "WABA-level rate limit hit", errorClass: "RETRY_BACKOFF", userFacingExplanation: "Backoff." },
  { apiSurface: "/messages", code: "130429", title: "Cloud API throughput ceiling reached", errorClass: "RETRY_BACKOFF", userFacingExplanation: "Reduce send rate; see §13 Sending engine." },
  { apiSurface: "/block_users", code: "130429", title: "Graph API request rate limit on the block-users endpoint", errorClass: "RETRY_BACKOFF", userFacingExplanation: "Backoff the block/unblock worker only — do not throttle sending." },
  { apiSurface: "/messages", code: "131056", title: "Pair rate limit — too many messages to the same person too fast", errorClass: "RETRY_BACKOFF", userFacingExplanation: "Per-recipient backoff (Meta suggests 4^X seconds)." },
  { apiSurface: "*", code: "131057", title: "Number in maintenance, or mid throughput upgrade", errorClass: "RETRY_BACKOFF", userFacingExplanation: "Retry after ~1 minute." },
  { apiSurface: "*", code: "2", title: "Temporary service unavailability at Meta", errorClass: "RETRY_BACKOFF", userFacingExplanation: "Backoff." },
  { apiSurface: "*", code: "131016", title: "Temporary service unavailability at Meta", errorClass: "RETRY_BACKOFF", userFacingExplanation: "Backoff." },
  { apiSurface: "*", code: "133004", title: "Temporary service unavailability at Meta", errorClass: "RETRY_BACKOFF", userFacingExplanation: "Backoff." },
  { apiSurface: "/messages", code: "131000", title: "Unknown send error", errorClass: "RETRY_BACKOFF", userFacingExplanation: "Bounded retries, then terminal." },
  { apiSurface: "/messages", code: "131047", title: "The 24-hour customer service window has expired", errorClass: "CONDITIONAL", userFacingExplanation: "Do not retry until the window reopens. Offer an approved template instead." },
  { apiSurface: "/block_users", code: "131047", title: "Target has not messaged this number in the last 24 hours, so it cannot be blocked", errorClass: "TERMINAL", userFacingExplanation: "Do not retry. Suppress locally instead of blocking at Meta." },
  { apiSurface: "/messages", code: "131049", title: "Meta's per-user marketing frequency cap blocked this message", errorClass: "CONDITIONAL", userFacingExplanation: "Never blind-retry; never retry within 24 hours. Report as 'blocked by frequency cap' — a non-delivery component, never a failure." },
  { apiSurface: "/messages", code: "131050", title: "User opted out of marketing from this business", errorClass: "TERMINAL", userFacingExplanation: "Write to suppression list." },
  { apiSurface: "/messages", code: "131048", title: "Spam rate limit — earlier messages were blocked or flagged", errorClass: "TERMINAL", userFacingExplanation: "Operational alert; pause the campaign." },
  { apiSurface: "/messages", code: "131021", title: "Sender and recipient are the same number", errorClass: "TERMINAL", userFacingExplanation: "Validation bug — fix." },
  { apiSurface: "/block_users", code: "131021", title: "Attempt to block the sender's own number (self-block)", errorClass: "TERMINAL", userFacingExplanation: "Validation bug — filter the business's own numbers out of block requests." },
  { apiSurface: "/messages", code: "131051", title: "Unsupported message type", errorClass: "TERMINAL", userFacingExplanation: "Fix payload." },
  { apiSurface: "/messages", code: "131403", title: "The business has blocked this user", errorClass: "TERMINAL", userFacingExplanation: "Suppress." },
  { apiSurface: "/messages", code: "131026", title: "Message undeliverable", errorClass: "PROBABLE_INVALID_CONTACT", userFacingExplanation: "Record a strike; never invalidate on one hit (see §8 / DM-22).", countsToward131026Evidence: true },
  { apiSurface: "/messages", code: "132015", title: "Template paused for low quality; also the drop code for template-pacing kills", errorClass: "TERMINAL", userFacingExplanation: "Edit the template; do not retry." },
  { apiSurface: "/messages", code: "135000", title: "Business portfolio pacing dropped the remaining queue", errorClass: "TERMINAL", userFacingExplanation: "Surface to the user; the rest of the campaign did not send." },
  { apiSurface: "/messages", code: "132000", title: "Wrong number of template parameters", errorClass: "TERMINAL", userFacingExplanation: "Fix the template call." },
  { apiSurface: "/messages", code: "132001", title: "Template not approved, or wrong language", errorClass: "TERMINAL", userFacingExplanation: "Fix. The sending engine must not have released this message at all — see the template status gate in §11." },
  { apiSurface: "/messages", code: "132005", title: "Translated text too long", errorClass: "TERMINAL", userFacingExplanation: "Fix." },
  { apiSurface: "/messages", code: "132007", title: "Policy violation in the template", errorClass: "TERMINAL", userFacingExplanation: "Rewrite and resubmit." },
  { apiSurface: "/messages", code: "132012", title: "Parameter format or validation error", errorClass: "TERMINAL", userFacingExplanation: "Fix." },
  { apiSurface: "/messages", code: "132018", title: "Parameter format or validation error", errorClass: "TERMINAL", userFacingExplanation: "Fix." },
  { apiSurface: "/messages", code: "132016", title: "Template permanently disabled", errorClass: "TERMINAL", userFacingExplanation: "Create a new template." },
  { apiSurface: "/messages", code: "131064", title: "Template-classification enforcement limit", errorClass: "CONDITIONAL", userFacingExplanation: "Wait out the enforcement window, then resume." },
  { apiSurface: "/messages", code: "132068", title: "Flow blocked", errorClass: "CONDITIONAL", userFacingExplanation: "Fix the Flow." },
  { apiSurface: "/messages", code: "132069", title: "Flow throttled (10+ messages in an hour)", errorClass: "CONDITIONAL", userFacingExplanation: "Back off until the throttle window clears." },
  { apiSurface: "*", code: "131042", title: "Payment method problem", errorClass: "OPERATIONAL_ALERT", userFacingExplanation: "Blocks ALL sending. Page a human; do not retry." },
  { apiSurface: "*", code: "131045", title: "Number not registered", errorClass: "OPERATIONAL_ALERT", userFacingExplanation: "Re-register (carefully — see 133016)." },
  { apiSurface: "*", code: "133010", title: "Number not registered", errorClass: "OPERATIONAL_ALERT", userFacingExplanation: "Re-register (carefully — see 133016)." },
  { apiSurface: "*", code: "368", title: "Account restricted / country restriction / account lock", errorClass: "OPERATIONAL_ALERT", userFacingExplanation: "Stop all sending, notify, appeal." },
  { apiSurface: "*", code: "130497", title: "Account restricted / country restriction / account lock", errorClass: "OPERATIONAL_ALERT", userFacingExplanation: "Stop all sending, notify, appeal." },
  { apiSurface: "*", code: "131031", title: "Account restricted / country restriction / account lock", errorClass: "OPERATIONAL_ALERT", userFacingExplanation: "Stop all sending, notify, appeal." },
  { apiSurface: "*", code: "190", title: "Token expired or authentication failure", errorClass: "OPERATIONAL_ALERT", userFacingExplanation: "Re-authenticate. The 6-hourly token health check should normally catch this first." },
  { apiSurface: "*", code: "0", title: "Token expired or authentication failure", errorClass: "OPERATIONAL_ALERT", userFacingExplanation: "Re-authenticate." },
  { apiSurface: "*", code: "200", title: "Token expired or authentication failure", errorClass: "OPERATIONAL_ALERT", userFacingExplanation: "Re-authenticate." },
  { apiSurface: "*", code: "131037", title: "Display name not approved", errorClass: "OPERATIONAL_ALERT", userFacingExplanation: "Fix in WhatsApp Manager." },
  { apiSurface: "/messages", code: "131053", title: "Media upload failure", errorClass: "TERMINAL", userFacingExplanation: "Fix the asset." },
  { apiSurface: "/register", code: "133005", title: "Two-step PIN wrong", errorClass: "OPERATIONAL_ALERT", userFacingExplanation: "133008 and 133009 carry a retry-after value — honour it." },
  { apiSurface: "/register", code: "133008", title: "Two-step PIN locked out", errorClass: "OPERATIONAL_ALERT", userFacingExplanation: "Honour the retry-after value." },
  { apiSurface: "/register", code: "133009", title: "Two-step PIN entered too fast", errorClass: "OPERATIONAL_ALERT", userFacingExplanation: "Honour the retry-after value." },
  { apiSurface: "/register", code: "133015", title: "Number was recently deleted", errorClass: "RETRY_BACKOFF", userFacingExplanation: "Wait 5 minutes." },
  { apiSurface: "/register", code: "133016", title: "Registration attempt limit reached", errorClass: "OPERATIONAL_ALERT", userFacingExplanation: "The number is locked for 72 hours. Guard with an internal counter BEFORE this is ever returned (refuse the 8th attempt with typed confirmation, refuse the 11th unconditionally)." },
  { apiSurface: "/deregister", code: "133016", title: "Deregistration attempt limit reached", errorClass: "OPERATIONAL_ALERT", userFacingExplanation: "The number is locked for 72 hours. Two independent counters — see §7 / DM-21." },
  { apiSurface: "*", code: "2388012", title: "Migration error", errorClass: "OPERATIONAL_ALERT", userFacingExplanation: "Manual intervention." },
  { apiSurface: "*", code: "2388091", title: "Migration error", errorClass: "OPERATIONAL_ALERT", userFacingExplanation: "Manual intervention." },
  { apiSurface: "*", code: "2388093", title: "Migration error", errorClass: "OPERATIONAL_ALERT", userFacingExplanation: "Manual intervention." },
  { apiSurface: "*", code: "2388103", title: "Migration error", errorClass: "OPERATIONAL_ALERT", userFacingExplanation: "Manual intervention." },
] as const;
